---
# https://www.ansible.com/blog/using-ansible-to-mitigate-network-vulnerabilities
- name: CVE example for Cisco router 
  hosts: cisco
  gather_facts: false
  tasks:
    - name: run show vstack config
        ios_command:
          commands:
            - show vstack config
        register: showvstack    

    - name: Check to make sure Cisco's Smart Install Client Feature is not enabled (1/2)
      assert:
        that:
          - "'SmartInstall enabled' not in showvstack.stdout"
          - "'Role' not in showvstack.stdout"
          - "'Client' not in showvstack.stdout" 